first-round-time: 10.0
min-round-time: 5.0
max-rounds: 10
grace-period: 5.0
whitelisted-blocks:
- ==: septusten.plugins.blockshuffle.BS_Block
  block: ACACIA_LOG
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: ACACIA_PLANKS
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: ACACIA_WOOD
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: ANDESITE
  weight: 50
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BARREL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BEDROCK
  weight: 50
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BEEHIVE
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BEE_NEST
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BIRCH_LOG
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BIRCH_PLANKS
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BIRCH_WOOD
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BLACK_GLAZED_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BLACK_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BLACK_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BLAST_FURNACE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BLUE_CONCRETE
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BLUE_CONCRETE_POWDER
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BLUE_ICE
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BLUE_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BONE_BLOCK
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BOOKSHELF
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BRAIN_CORAL_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BRICKS
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BROWN_GLAZED_TERRACOTTA
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BROWN_MUSHROOM_BLOCK
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BROWN_TERRACOTTA
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BROWN_WOOL
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: BUBBLE_CORAL_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CARTOGRAPHY_TABLE
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CARVED_PUMPKIN
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CHISELED_QUARTZ_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CHISELED_RED_SANDSTONE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CHISELED_SANDSTONE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CHISELED_STONE_BRICKS
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CLAY
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: COAL_BLOCK
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: COAL_ORE
  weight: 50
- ==: septusten.plugins.blockshuffle.BS_Block
  block: COARSE_DIRT
  weight: 50
- ==: septusten.plugins.blockshuffle.BS_Block
  block: COBBLESTONE
  weight: 50
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CRACKED_STONE_BRICKS
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CRAFTING_TABLE
  weight: 50
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CUT_RED_SANDSTONE
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CUT_SANDSTONE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CYAN_CONCRETE
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CYAN_CONCRETE_POWDER
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: CYAN_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DARK_OAK_LOG
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DARK_OAK_PLANKS
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DARK_OAK_WOOD
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DEAD_BRAIN_CORAL_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DEAD_BUBBLE_CORAL_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DEAD_FIRE_CORAL_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DEAD_HORN_CORAL_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DEAD_TUBE_CORAL_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DIAMOND_BLOCK
  weight: 1
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DIAMOND_ORE
  weight: 10
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DIORITE
  weight: 50
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DIRT
  weight: 50
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DISPENSER
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DRIED_KELP_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: DROPPER
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: EMERALD_BLOCK
  weight: 1
- ==: septusten.plugins.blockshuffle.BS_Block
  block: EMERALD_ORE
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: END_STONE
  weight: 1
- ==: septusten.plugins.blockshuffle.BS_Block
  block: END_STONE_BRICKS
  weight: 1
- ==: septusten.plugins.blockshuffle.BS_Block
  block: FIRE_CORAL_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: FLETCHING_TABLE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: FURNACE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: GOLD_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: GOLD_ORE
  weight: 10
- ==: septusten.plugins.blockshuffle.BS_Block
  block: GRANITE
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: GRASS_BLOCK
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: GRAVEL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: GRAY_CONCRETE
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: GRAY_CONCRETE_POWDER
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: GRAY_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: GREEN_CONCRETE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: GREEN_CONCRETE_POWDER
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: GREEN_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: HAY_BLOCK
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: HONEYCOMB_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: HORN_CORAL_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: IRON_BLOCK
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: IRON_ORE
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: JACK_O_LANTERN
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: JIGSAW
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: JUKEBOX
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: JUNGLE_LOG
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: JUNGLE_PLANKS
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: JUNGLE_WOOD
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LAPIS_BLOCK
  weight: 10
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LAPIS_ORE
  weight: 10
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LIGHT_BLUE_GLAZED_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LIGHT_BLUE_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LIGHT_BLUE_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LIGHT_GRAY_GLAZED_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LIGHT_GRAY_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LIGHT_GRAY_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LIME_CONCRETE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LIME_CONCRETE_POWDER
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LIME_GLAZED_TERRACOTTA
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LIME_TERRACOTTA
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LIME_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: LOOM
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: MAGENTA_CONCRETE
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: MAGENTA_CONCRETE_POWDER
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: MAGENTA_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: MAGMA_BLOCK
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: MELON
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: MUSHROOM_STEM
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: MYCELIUM
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: NETHERRACK
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: NETHER_BRICKS
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: NETHER_QUARTZ_ORE
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: NETHER_WART_BLOCK
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: NOTE_BLOCK
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: OAK_LOG
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: OAK_PLANKS
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: OAK_WOOD
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: OBSIDIAN
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: ORANGE_CONCRETE
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: ORANGE_CONCRETE_POWDER
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: ORANGE_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PACKED_ICE
  weight: 3
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PINK_CONCRETE
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PINK_CONCRETE_POWDER
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PINK_GLAZED_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PINK_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PINK_WOOL
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PODZOL
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: POLISHED_ANDESITE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: POLISHED_DIORITE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: POLISHED_GRANITE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PRISMARINE
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PRISMARINE_BRICKS
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PUMPKIN
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PURPLE_CONCRETE
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PURPLE_CONCRETE_POWDER
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PURPLE_GLAZED_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PURPLE_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PURPLE_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PURPUR_BLOCK
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: PURPUR_PILLAR
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: QUARTZ_BLOCK
  weight: 10
- ==: septusten.plugins.blockshuffle.BS_Block
  block: QUARTZ_PILLAR
  weight: 10
- ==: septusten.plugins.blockshuffle.BS_Block
  block: REDSTONE_LAMP
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: REDSTONE_ORE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: RED_CONCRETE
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: RED_CONCRETE_POWDER
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: RED_GLAZED_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: RED_MUSHROOM_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: RED_NETHER_BRICKS
  weight: 10
- ==: septusten.plugins.blockshuffle.BS_Block
  block: RED_SAND
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: RED_SANDSTONE
  weight: 10
- ==: septusten.plugins.blockshuffle.BS_Block
  block: RED_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: RED_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SAND
  weight: 50
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SANDSTONE
  weight: 50
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SLIME_BLOCK
  weight: 3
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SMITHING_TABLE
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SMOKER
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SMOOTH_QUARTZ
  weight: 10
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SMOOTH_RED_SANDSTONE
  weight: 1
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SMOOTH_SANDSTONE
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SMOOTH_STONE
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SNOW_BLOCK
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SOUL_SAND
  weight: 15
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SPAWNER
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SPONGE
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SPRUCE_LOG
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SPRUCE_PLANKS
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: SPRUCE_WOOD
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STONE
  weight: 50
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STONE_BRICKS
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STRIPPED_ACACIA_LOG
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STRIPPED_ACACIA_WOOD
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STRIPPED_BIRCH_LOG
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STRIPPED_BIRCH_WOOD
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STRIPPED_DARK_OAK_LOG
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STRIPPED_DARK_OAK_WOOD
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STRIPPED_JUNGLE_LOG
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STRIPPED_JUNGLE_WOOD
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STRIPPED_OAK_LOG
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STRIPPED_OAK_WOOD
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STRIPPED_SPRUCE_LOG
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: STRIPPED_SPRUCE_WOOD
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: TUBE_CORAL_BLOCK
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: WET_SPONGE
  weight: 5
- ==: septusten.plugins.blockshuffle.BS_Block
  block: WHITE_CONCRETE
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: WHITE_CONCRETE_POWDER
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: WHITE_GLAZED_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: WHITE_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: WHITE_WOOL
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: YELLOW_CONCRETE
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: YELLOW_CONCRETE_POWDER
  weight: 30
- ==: septusten.plugins.blockshuffle.BS_Block
  block: YELLOW_GLAZED_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: YELLOW_TERRACOTTA
  weight: 20
- ==: septusten.plugins.blockshuffle.BS_Block
  block: YELLOW_WOOL
  weight: 30